///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: resources/fondo.aks
/// Generation time: ma., 25 de oct. de 2016 17:53:41
///

/// Song 'g_mysong' metadata macros
#define g_mysong_address  0x200
#define g_mysong_size     266
#define g_mysong_end      0x

/// Song 'g_mysong' array declaration
extern void g_mysong[g_mysong_size];
